# Generated by Django 5.1.1 on 2024-10-14 19:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_remove_contactinfo_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='work_schedule',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
