# Generated by Django 5.1.1 on 2024-10-27 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='photo',
        ),
    ]
