# Generated by Django 5.1.1 on 2024-09-15 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerReview',
        ),
    ]
