# Generated by Django 5.1.1 on 2024-10-27 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_establishment_compleate_projects_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='compleate_projects',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='expert_technicians',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='phone',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='satisfies_clients',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='years_experience',
            field=models.CharField(max_length=255),
        ),
    ]
