# Generated by Django 5.1.1 on 2024-10-26 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='experience_text',
            field=models.CharField(default='Years Experience', max_length=50),
        ),
        migrations.AddField(
            model_name='about',
            name='experience_years',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='AboutFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='about.about')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
